# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6001bfc3fb457ab5d4320b5e08c305524259fd2f3763c695824bc7cd616c4e6d34b2bb3c159cd32fcc9a315f2701958da34262a220a09ef2f750f4e0610e0bb8

test:
  secret_key_base: b8ebf21ab07001ec5329274ed2f48b6b3268b684ec37ad6ababfff5acd4e47b23aa82bb56ac7036ce0c1485ad644c6e6a73d75881c28ea69effa648252916b4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
